-- 코드를 입력하세요
# 문제 위에 2줄
#SELECT CAR_ID, COUNT(CAR_ID)
#FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01' 
#GROUP BY CAR_ID HAVING COUNT(CAR_ID) > 4

SELECT DATE_FORMAT(START_DATE, "%m") AS MONTH, CAR_ID, COUNT(car_id) AS RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01' AND CAR_ID 
IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01' 
    GROUP BY CAR_ID 
    HAVING COUNT(CAR_ID) > 4)  
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC;




