-- 코드를 입력하세요
#  2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일을 조회
SELECT TITLE, USED_GOODS_BOARD.BOARD_ID, REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD
INNER JOIN USED_GOODS_REPLY 
ON USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
#WHERE USED_GOODS_BOARD.CREATED_DATE LIKE "2022-10%" # 날짜 이상 미만으로 해도됨
#WHERE USED_GOODS_BOARD.CREATED_DATE BETWEEN "2022-10-01" AND "2022-10-31"
WHERE USED_GOODS_BOARD.CREATED_DATE >= "2022-10-01" 
AND USED_GOODS_BOARD.CREATED_DATE <= "2022-10-31"
ORDER BY USED_GOODS_REPLY.CREATED_DATE, USED_GOODS_BOARD.TITLE;