-- 코드를 입력하세요
# 22-01 카테고리 도서별 판매량, 카테고리
SELECT CATEGORY, SUM(SALES) FROM BOOK
RIGHT JOIN BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE BOOK_SALES.SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY 
ORDER BY CATEGORY  